[[redirects]]
  from = "/api/proxy"
  to = "https://script.google.com/macros/s/AKfycbyUP8wHkErf7a20HJemThwY4Vq0xjQiCskpXDWwqysG2y3BCKMulLTRZ7-Fs0LbFoBacg/exec"
  status = 200
  force = true

[[redirects]]
  from = "/julius-welt.html"
  to = "/julius-welt.html"
  status = 200
  force = true

[[redirects]]
  from = "https://anmeldung.onlang.de/*"
  to = "/anmeldung.html"
  status = 200

[[redirects]]
  from = "https://admin.onlang.de/*"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "https://dashboard.onlang.de/*"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "CI= npm run build"
  publish = "build"

[[edge_functions]]
  path = "/manifest.json"
  function = "manifest"
